In [1]:
import GetOldTweets3 as got
import numpy as np
import pandas as pd
import datetime
import time

In [2]:
def get_month_tweets2(month,query,start_day=1,y=2020, hashtag=False):
    date_date = datetime.date.today().replace(year=y).replace(day=start_day).replace(month=month)
    next_date = date_date + datetime.timedelta(days=1)

    next_month = datetime.date.today().replace(year=y).replace(day=28).replace(month=month)\
    + datetime.timedelta(days=4)
    until_date= next_month - datetime.timedelta(days=next_month.day)
    until_date = until_date.strftime("%Y-%m-%d")
    
    today = datetime.date.today().strftime("%Y-%m-%d")
    
    while date_date.strftime("%Y-%m-%d") <= until_date and date_date.strftime("%Y-%m-%d") < today:
        incomplete = True
        while incomplete:
            try:
                tweetCriteria = got.manager.TweetCriteria().setQuerySearch(query)\
                .setSince(date_date.strftime("%Y-%m-%d")).setUntil(next_date.strftime("%Y-%m-%d"))
                # Creation of list that contains all tweets
                tweets = got.manager.TweetManager.getTweets(tweetCriteria)
                # Creating list of chosen tweet data
                text_tweets = [[tweet.id,tweet.date,tweet.username, tweet.text,tweet.hashtags,tweet.geo,\
                                tweet.retweets,tweet.favorites,tweet.mentions,tweet.to] for tweet in tweets]

                df = pd.DataFrame(text_tweets, columns=["id","timestamp","username","text","hashtags","geo","retweets","favorites","mentions","to"])
                df["date"] = df.timestamp.dt.date

                store_csv2(df,month,y,hashtag)

                print(date_date.strftime("%Y-%m-%d"), len(text_tweets))
                date_date = date_date + datetime.timedelta(days=1)
                next_date = next_date + datetime.timedelta(days=1)
                
                incomplete = False
                
            except:
                print("Request error")
                time.sleep(60*1)
    
    hasht=""
    if hashtag:
        hasht = "hashtag_"
        
    file_name = f'data/{y}/{hasht}census_tweets_month_{month}.csv'
    
    df = pd.read_csv(file_name)
    return df

def store_csv2(df,month,y=2020,hashtag=False):
    hasht=""
    if hashtag:
        hasht = "hashtag_"
        
    file_name = f'data/{y}/{hasht}census_tweets_month_{month}.csv'
    
    df.to_csv(file_name,mode = 'a', header= False, index = False)

In [3]:
def update_month(year,month,query):
    hashtag = "#" in query
    if hashtag:
        file_name = f"data/{year}/hashtag_census_tweets_month_{month}.csv"
    else:
        file_name = f"data/{year}/census_tweets_month_{month}.csv"
    
    file = pd.read_csv(file_name, parse_dates=["date"]).sort_values(by=["date"],ascending=False)
    date = file.date.dt.date.max() + datetime.timedelta(days=1)
    day = date.day
    if date.month==month:
        return get_month_tweets2(month, query, start_day=day,y=year, hashtag=hashtag )

In [4]:
q = "#2020census OR #census2020"
df = update_month(2020,5,q)
df

2020-05-15 792

,id,timestamp,username,text,hashtags,geo,retweets,favorites,mentions,to,date
0,1256372334086291457,2020-05-01 23:58:01+00:00,ForOurFutureNV,Did you complete your #2020Census yet? Did you...,#2020Census,NaN,7,9,NaN,NaN,2020-05-01
1,1256372275143749634,2020-05-01 23:57:47+00:00,robachma,#2020Census,#2020Census,NaN,0,1,NaN,GregMartinMusic,2020-05-01
2,1256372204947812356,2020-05-01 23:57:30+00:00,ISRAELPROPHET,Message: Why respond to the #2020Census? Censu...,#2020Census,NaN,0,0,NaN,NaN,2020-05-01
3,1256372053009223682,2020-05-01 23:56:54+00:00,ISRAELPROPHET1,Message: Why respond to the #2020Census? Censu...,#2020Census,NaN,1,1,NaN,NaN,2020-05-01
4,1256371553698078722,2020-05-01 23:54:55+00:00,CityFortBraggCA,Did you know the #2020census is required by th...,#2020census #censusfacts,NaN,0,2,NaN,NaN,2020-05-01
...,...,...,...,...,...,...,...,...,...,...,...
14539,1261083971741417474,2020-05-15 00:00:23+00:00,ActionAAPI,Let's #GetCounted! It's crucial to ensure that...,#GetCounted #2020Census,NaN,0,0,NaN,AAFederation,2020-05-15
14540,1261083944470142976,2020-05-15 00:00:16+00:00,2020Mississippi,"Next Tuesday, May 19th at 2:00 p.m., the Unite...",#2020Census,NaN,0,1,NaN,NaN,2020-05-15
14541,1261083901231009792,2020-05-15 00:00:06+00:00,HealthyLeeTweet,"From health clinics to fire departments, schoo...",#Census2020 #ShapeYourFuture,NaN,0,1,NaN,NaN,2020-05-15
14542,1261083890136920065,2020-05-15 00:00:03+00:00,ConsulMexPho,¿Aún no respondido al #2020Census? Te comparti...,#2020Census #HazteContar #PasaLaVoz,NaN,0,0,NaN,NaN,2020-05-15
14543,1261083876769665025,2020-05-15 00:00:00+00:00,TrueNorth_CS,"No matter where or what you call home, the #20...",#2020Census,NaN,0,0,NaN,NaN,2020-05-15

In [4]:
text_query = "census"
# text_query = "#2020census OR #census2020"
df = update_month(2020,4,text_query)
df

An error occured during an HTTP request: HTTP Error 503: Service Temporarily Unavailable
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-10%20until%3A2020-04-11&src=typd
Request error
2020-04-10 3514
2020-04-11 3055
An error occured during an HTTP request: HTTP Error 503: Service Temporarily Unavailable
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-12%20until%3A2020-04-13&src=typd
Request error
An error occured during an HTTP request: HTTP Error 503: Service Temporarily Unavailable
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-12%20until%3A2020-04-13&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-12%20until%3A2020-04-13&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-12%20until%3A2020-04-13&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-12%20until%3A2020-04-13&src=typd
Request error
2020-04-12 2950
2020-04-13 4381
2020-04-14 4832
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-15%20until%3A2020-04-16&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-15%20until%3A2020-04-16&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-15%20until%3A2020-04-16&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-15%20until%3A2020-04-16&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-15%20until%3A2020-04-16&src=typd
Request error
2020-04-15 4188
2020-04-16 4302
2020-04-17 3486
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-18%20until%3A2020-04-19&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-18%20until%3A2020-04-19&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-18%20until%3A2020-04-19&src=typd
Request error
2020-04-18 2450
2020-04-19 2222
2020-04-20 3182
2020-04-21 3370
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-22%20until%3A2020-04-23&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-22%20until%3A2020-04-23&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-22%20until%3A2020-04-23&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-22%20until%3A2020-04-23&src=typd
Request error
2020-04-22 3144
2020-04-23 3307
2020-04-24 2786
2020-04-25 2050
2020-04-26 2211
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-27%20until%3A2020-04-28&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-27%20until%3A2020-04-28&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-27%20until%3A2020-04-28&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-27%20until%3A2020-04-28&src=typd
Request error
An error occured during an HTTP request: HTTP Error 429: Too Many Requests
Try to open in browser: https://twitter.com/search?q=census%20since%3A2020-04-27%20until%3A2020-04-28&src=typd
Request error
2020-04-27 3120
2020-04-28 3298
2020-04-29 3049
2020-04-30 3320

,id,timestamp,username,text,hashtags,geo,retweets,favorites,mentions,to,date
0,1245863530223374336,2020-04-02 23:59:47+00:00,evduzit,Oh it’s Census time??,NaN,NaN,0,1,NaN,NaN,2020-04-02
1,1245863445259415558,2020-04-02 23:59:27+00:00,Ujamidaize,No ooo... I just came to do census for Angel Gabe,NaN,NaN,0,0,NaN,ETUKMMA,2020-04-02
2,1245863357149614080,2020-04-02 23:59:06+00:00,tonetalks,“African Americans account for 35% of cases & ...,NaN,NaN,19,30,@MehrsaBaradaran,kat__stafford,2020-04-02
3,1245863341693648897,2020-04-02 23:59:02+00:00,HermistonHerald,You know what's a great quarantine activity? F...,NaN,NaN,0,0,NaN,NaN,2020-04-02
4,1245863156879986689,2020-04-02 23:58:18+00:00,Zach_Case_,I’m 28 years old and just completed my first c...,NaN,NaN,0,3,NaN,NaN,2020-04-02
...,...,...,...,...,...,...,...,...,...,...,...
105862,1255648241309421568,2020-04-30 00:00:44+00:00,linc_nyc,#2020Census is a chance to shape your communit...,#2020Census #GetCountedNYC #2020Census #LetALL...,NaN,3,3,NaN,NaN,2020-04-30
105863,1255648185604857856,2020-04-30 00:00:30+00:00,AR_CAA,AR is only just shy of hitting the 50% census ...,NaN,NaN,1,2,NaN,NaN,2020-04-30
105864,1255648099969662988,2020-04-30 00:00:10+00:00,CalEndow,African Americans have historically been under...,#Census2020 #EveryoneCounts,NaN,3,5,NaN,NaN,2020-04-30
105865,1255648093992898561,2020-04-30 00:00:09+00:00,RockTheVote,Black millennials and generation Z---you have ...,#CountMeBlack #CountBlackYouth,NaN,6,13,NaN,NaN,2020-04-30
105866,1255648058907463681,2020-04-30 00:00:00+00:00,PresenteOrg,"You can fill out the census online, over the p...",#WeMustCount #2020Census,NaN,0,0,NaN,NaN,2020-04-30